services:
  strapi:
    networks:
      - traefik
    labels:
      - "traefik.enable=true"

      # HTTPS
      - "traefik.http.routers.konoiko-strapi.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/strapi`)"
      - "traefik.http.middlewares.strip-strapi.stripprefix.prefixes=/strapi"
      - "traefik.http.routers.jtap-strapi.middlewares=strip-strapi"
      - "traefik.http.routers.konoiko-strapi.entrypoints=websecure"
      - "traefik.http.routers.konoiko-strapi.tls.certresolver=myresolver"
      - "traefik.http.services.konoiko-strapi.loadbalancer.server.port=${PORT_BACKEND}"

      # HTTP redirect
      - "traefik.http.routers.konoiko-strapi-http.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/strapi`)"
      - "traefik.http.routers.konoiko-strapi-http.entrypoints=web"
      - "traefik.http.routers.konoiko-strapi-http.middlewares=https-redirect"

  nuxt:
    networks:
      - traefik
    labels:
      - "traefik.enable=true"

      # HTTPS
      - "traefik.http.routers.konoiko.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.konoiko.entrypoints=websecure"
      - "traefik.http.routers.konoiko.tls.certresolver=myresolver"
      - "traefik.http.services.konoiko.loadbalancer.server.port=${PORT_FRONTEND}"

      # HTTP redirect
      - "traefik.http.routers.konoiko-http.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.konoiko-http.entrypoints=web"
      - "traefik.http.routers.konoiko-http.middlewares=https-redirect"

      # Middleware definition
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
