services:
  strapi:
    labels:
      - "traefik.enable=true"

      # HTTPS
      - "traefik.http.routers.strapi.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/strapi`)"
      - "traefik.http.routers.strapi.entrypoints=websecure"
      - "traefik.http.routers.strapi.tls.certresolver=myresolver"
      - "traefik.http.routers.strapi.middlewares=strapi-stripprefix"
      - "traefik.http.middlewares.strapi-stripprefix.stripprefix.prefixes=/strapi"
      - "traefik.http.services.strapi.loadbalancer.server.port=${PORT_BACKEND}"

      # HTTP redirect
      - "traefik.http.routers.strapi-http.rule=Host(`${TRAEFIK_DOMAIN}`) && PathPrefix(`/strapi`)"
      - "traefik.http.routers.strapi-http.entrypoints=web"
      - "traefik.http.routers.strapi-http.middlewares=https-redirect,strapi-stripprefix"

  nuxt:
    labels:
      - "traefik.enable=true"

      # HTTPS
      - "traefik.http.routers.nuxt.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.nuxt.entrypoints=websecure"
      - "traefik.http.routers.nuxt.tls.certresolver=myresolver"
      - "traefik.http.services.nuxt.loadbalancer.server.port=${PORT_FRONTEND}"

      # HTTP redirect
      - "traefik.http.routers.nuxt-http.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.nuxt-http.entrypoints=web"
      - "traefik.http.routers.nuxt-http.middlewares=https-redirect"

      # Middleware definition
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"


networks:
  traefik:
    external: true
