/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import dragDropContentTypes from "@retikolo/drag-drop-content-types/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import relationsSelect from "../../src/plugins/relations-select/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "drag-drop-content-types": dragDropContentTypes,
    "color-picker": colorPicker,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "multi-select": multiSelect,
    "relations-select": relationsSelect,
  },
});
